server:
  port: 8080

management:
  server:
    port: 8081
    address: 0.0.0.0
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
    web: info
    sql: info

http:
  out:
    hmt:
      host: http://exc-mock-application:8083
