server:
  port: 8089
  shutdown: graceful

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

management:
  server:
    port: 8082
    address: 0.0.0.0
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, shutdown

logging:
  level:
    root: info
    web: info

# External HTTP Services
http:
  out:
    tmdb:
      host: https://api.themoviedb.org
      authorization-token: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZDg4NWY2OWU5NzQ3YTM3YzY0YmM3MmVjOTY2Y2YwMiIsIm5iZiI6MTcyMDAxMzM1MC44NDY2ODQsInN1YiI6IjUyNTdjZTc1NzYwZWUzNzMwNzA0MjlhMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.U65F-bOQ2KkydfakMU9jLzQ6vWR65oKYKQpvmhs0ylk"
      read-timeout: 2000
      connection-timeout: 2000
      max-idle-connections: 10
      keep-alive: 300000

